jobs:
  updateBlog:
    name: update blog site
    steps:
      - name: step1
        timeout-minutes: 1
        work-dir: /data/www/inhere
        run: |
          git checkout .
          git pull -f
